/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  CharacterCharacteristics,  CharacterState,  Grade,  HistoryItem,  PerceivedProsody,  ProsodyScores,  ResponseNote,  Update,  VoiceDirections } from "../types"

import type * as types from "../types"

/**
 * Streaming BAML server actions that return ReadableStreams.
 */

/**
 * Executes the streaming variant of the "DeriveVoice" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } character_message - Input parameter.
 * @param { types.CharacterCharacteristics } character_characteristics - Input parameter.
 * @param { types.CharacterState } character_state - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const DeriveVoice = async (
  character_message: string,
  character_characteristics: types.CharacterCharacteristics,
  character_state: types.CharacterState,
): Promise<ReadableStream<Uint8Array>> => {
  const __stream__ = b.stream.DeriveVoice(
    character_message,
    character_characteristics,
    character_state,
  );
  return Promise.resolve(__stream__.toStreamable());
};

/**
 * Executes the streaming variant of the "FilterPerception" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { types.ProsodyScores } raw_prosody - Input parameter.
 * @param { types.CharacterCharacteristics } character_characteristics - Input parameter.
 * @param { types.CharacterState } character_state - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const FilterPerception = async (
  raw_prosody: types.ProsodyScores,
  character_characteristics: types.CharacterCharacteristics,
  character_state: types.CharacterState,
): Promise<ReadableStream<Uint8Array>> => {
  const __stream__ = b.stream.FilterPerception(
    raw_prosody,
    character_characteristics,
    character_state,
  );
  return Promise.resolve(__stream__.toStreamable());
};

/**
 * Executes the streaming variant of the "GradeActiveListening" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } scenario - Input parameter.
 * @param { types.HistoryItem[] } history - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const GradeActiveListening = async (
  scenario: string,
  history: types.HistoryItem[],
): Promise<ReadableStream<Uint8Array>> => {
  const __stream__ = b.stream.GradeActiveListening(
    scenario,
    history,
  );
  return Promise.resolve(__stream__.toStreamable());
};

/**
 * Executes the streaming variant of the "Talk" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { types.CharacterCharacteristics } character_characteristics - Input parameter.
 * @param { string } scenario - Input parameter.
 * @param { types.HistoryItem[] } history - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const Talk = async (
  character_characteristics: types.CharacterCharacteristics,
  scenario: string,
  history: types.HistoryItem[],
): Promise<ReadableStream<Uint8Array>> => {
  const __stream__ = b.stream.Talk(
    character_characteristics,
    scenario,
    history,
  );
  return Promise.resolve(__stream__.toStreamable());
};