/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  CoachCharacteristics,  CoachState,  Grade,  HistoryItem,  ResponseNote,  Update } from "../types"

import type * as types from "../types"

/**
 * Regular BAML server actions that return direct responses.
 */

/**
 * Executes the "GradeActiveListening" BAML action.
 *
 * This server action calls the underlying BAML function "GradeActiveListening"
 * with the specified parameters.
 *
 * @param { string } scenario - Input parameter.
 * @param { types.HistoryItem[] } history - Input parameter.
 *
 * @returns {Promise<types.Grade>} A promise that resolves with the result of the action.
 */
export const GradeActiveListening = async (
  scenario: string,
  history: types.HistoryItem[],
): Promise<types.Grade> => {
  return b.GradeActiveListening(
    scenario,
    history,
  );
};

/**
 * Executes the "Talk" BAML action.
 *
 * This server action calls the underlying BAML function "Talk"
 * with the specified parameters.
 *
 * @param { types.CoachCharacteristics } coach_characteristics - Input parameter.
 * @param { string } scenario - Input parameter.
 * @param { types.HistoryItem[] } history - Input parameter.
 *
 * @returns {Promise<types.Update>} A promise that resolves with the result of the action.
 */
export const Talk = async (
  coach_characteristics: types.CoachCharacteristics,
  scenario: string,
  history: types.HistoryItem[],
): Promise<types.Update> => {
  return b.Talk(
    coach_characteristics,
    scenario,
    history,
  );
};