/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  CharacterCharacteristics,  CharacterState,  Grade,  HistoryItem,  PerceivedProsody,  ProsodyScores,  ResponseNote,  Update,  VoiceDirections } from "../types"

import type * as types from "../types"

/**
 * Regular BAML server actions that return direct responses.
 */

/**
 * Executes the "DeriveVoice" BAML action.
 *
 * This server action calls the underlying BAML function "DeriveVoice"
 * with the specified parameters.
 *
 * @param { string } character_message - Input parameter.
 * @param { types.CharacterCharacteristics } character_characteristics - Input parameter.
 * @param { types.CharacterState } character_state - Input parameter.
 *
 * @returns {Promise<types.VoiceDirections>} A promise that resolves with the result of the action.
 */
export const DeriveVoice = async (
  character_message: string,
  character_characteristics: types.CharacterCharacteristics,
  character_state: types.CharacterState,
): Promise<types.VoiceDirections> => {
  return b.DeriveVoice(
    character_message,
    character_characteristics,
    character_state,
  );
};

/**
 * Executes the "FilterPerception" BAML action.
 *
 * This server action calls the underlying BAML function "FilterPerception"
 * with the specified parameters.
 *
 * @param { types.ProsodyScores } raw_prosody - Input parameter.
 * @param { types.CharacterCharacteristics } character_characteristics - Input parameter.
 * @param { types.CharacterState } character_state - Input parameter.
 *
 * @returns {Promise<types.PerceivedProsody>} A promise that resolves with the result of the action.
 */
export const FilterPerception = async (
  raw_prosody: types.ProsodyScores,
  character_characteristics: types.CharacterCharacteristics,
  character_state: types.CharacterState,
): Promise<types.PerceivedProsody> => {
  return b.FilterPerception(
    raw_prosody,
    character_characteristics,
    character_state,
  );
};

/**
 * Executes the "GradeActiveListening" BAML action.
 *
 * This server action calls the underlying BAML function "GradeActiveListening"
 * with the specified parameters.
 *
 * @param { string } scenario - Input parameter.
 * @param { types.HistoryItem[] } history - Input parameter.
 *
 * @returns {Promise<types.Grade>} A promise that resolves with the result of the action.
 */
export const GradeActiveListening = async (
  scenario: string,
  history: types.HistoryItem[],
): Promise<types.Grade> => {
  return b.GradeActiveListening(
    scenario,
    history,
  );
};

/**
 * Executes the "Talk" BAML action.
 *
 * This server action calls the underlying BAML function "Talk"
 * with the specified parameters.
 *
 * @param { types.CharacterCharacteristics } character_characteristics - Input parameter.
 * @param { string } scenario - Input parameter.
 * @param { types.HistoryItem[] } history - Input parameter.
 *
 * @returns {Promise<types.Update>} A promise that resolves with the result of the action.
 */
export const Talk = async (
  character_characteristics: types.CharacterCharacteristics,
  scenario: string,
  history: types.HistoryItem[],
): Promise<types.Update> => {
  return b.Talk(
    character_characteristics,
    scenario,
    history,
  );
};