/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  CoachCharacteristics,  Grade,  Statement } from "../types"

import type * as types from "../types"

/**
 * Streaming BAML server actions that return ReadableStreams.
 */

/**
 * Executes the streaming variant of the "GradeActiveListening" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } scenario - Input parameter.
 * @param { types.Statement[] } history - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const GradeActiveListening = async (
  scenario: string,
  history: types.Statement[],
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.GradeActiveListening(
    scenario,
    history,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "Talk" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { types.CoachCharacteristics } coach_characteristics - Input parameter.
 * @param { string } scenario - Input parameter.
 * @param { boolean } pretending - Input parameter.
 * @param { types.Statement[] } history - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const Talk = async (
  coach_characteristics: types.CoachCharacteristics,
  scenario: string,
  pretending: boolean,
  history: types.Statement[],
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.Talk(
    coach_characteristics,
    scenario,
    pretending,
    history,
  );
  return Promise.resolve(stream.toStreamable());
};