/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CoachCharacteristics,  CoachState,  Grade,  HistoryItem,  ResponseNote,  Update } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CoachCharacteristics {
      name?: string | null
      is_therapist?: boolean | null
      introversion?: number | null
      communication_skill?: number | null
      openness?: number | null
      conscientiousness?: number | null
      age?: number | null
      gender?: "male" | "female" | "nonbinary" | null
      nationality?: string | null
      reactivity?: number | null
      special_notes?: string | null
    }
    export interface CoachState {
      relaxed?: number | null
      nervous?: number | null
      openness?: number | null
      shy?: number | null
      aggressive?: number | null
      secretly_angry?: number | null
    }
    export interface Grade {
      letter_grade?: string | null
      effective_responses: ResponseNote[]
      areas_for_improvement: ResponseNote[]
      feedback?: string | null
    }
    export interface HistoryItem {
      text?: string | null
      speaker?: "user" | "ai" | null
      timestamp?: string | null
      coach_state?: CoachState | null
    }
    export interface ResponseNote {
      original_content?: string | null
      grader_note?: string | null
    }
    export interface Update {
      terminate_session?: boolean | null
      coach_state?: CoachState | null
      coach_message?: string | null
    }
}