/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CoachCharacteristics,  Grade,  Statement } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CoachCharacteristics {
      name?: string | null
      introversion?: number | null
      communication_skill?: number | null
      openness?: number | null
      conscientiousness?: number | null
      age?: number | null
      gender?: "male" | "female" | "other" | null
      nationality?: string | null
      reactivity?: number | null
    }
    export interface Grade {
      letter_grade?: string | null
      feedback?: string | null
    }
    export interface Statement {
      text?: string | null
      speaker?: "user" | "ai" | null
    }
}