/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CharacterCharacteristics,  CharacterState,  Grade,  HistoryItem,  PerceivedProsody,  ProsodyScores,  ResponseNote,  Update,  VoiceDirections } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CharacterCharacteristics {
      name?: string | null
      is_therapist?: boolean | null
      introversion?: number | null
      communication_skill?: number | null
      openness?: number | null
      conscientiousness?: number | null
      age?: number | null
      gender?: "male" | "female" | "nonbinary" | null
      nationality?: string | null
      reactivity?: number | null
      special_notes?: string | null
    }
    export interface CharacterState {
      relaxed?: number | null
      nervous?: number | null
      openness?: number | null
      shy?: number | null
      aggressive?: number | null
      secretly_angry?: number | null
    }
    export interface Grade {
      letter_grade?: string | null
      effective_responses: ResponseNote[]
      areas_for_improvement: ResponseNote[]
      feedback?: string | null
    }
    export interface HistoryItem {
      text?: string | null
      speaker?: "user" | "ai" | null
      timestamp?: string | null
      character_state?: CharacterState | null
      user_prosody?: PerceivedProsody | null
    }
    export interface PerceivedProsody {
      scores?: ProsodyScores | null
      perception_notes?: string | null
    }
    export interface ProsodyScores {
      admiration?: number | null
      adoration?: number | null
      amusement?: number | null
      anger?: number | null
      anxiety?: number | null
      awe?: number | null
      awkwardness?: number | null
      boredom?: number | null
      calmness?: number | null
      concentration?: number | null
      confusion?: number | null
      contempt?: number | null
      contentment?: number | null
      determination?: number | null
      disappointment?: number | null
      disgust?: number | null
      distress?: number | null
      doubt?: number | null
      embarrassment?: number | null
      excitement?: number | null
      fear?: number | null
      guilt?: number | null
      interest?: number | null
      joy?: number | null
      love?: number | null
      nostalgia?: number | null
      pain?: number | null
      pride?: number | null
      sadness?: number | null
      satisfaction?: number | null
      shame?: number | null
      surprise_negative?: number | null
      surprise_positive?: number | null
      sympathy?: number | null
      tiredness?: number | null
    }
    export interface ResponseNote {
      original_content?: string | null
      grader_note?: string | null
    }
    export interface Update {
      terminate_session?: boolean | null
      character_state?: CharacterState | null
      reasoning?: string | null
      character_message?: string | null
    }
    export interface VoiceDirections {
      description?: string | null
      speed?: number | null
    }
}