/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface CharacterCharacteristics {
  name: string
  is_therapist: boolean
  introversion: number
  communication_skill: number
  openness: number
  conscientiousness: number
  age: number
  gender: "male" | "female" | "nonbinary"
  nationality: string
  reactivity: number
  special_notes: string
  
}

export interface CharacterState {
  relaxed: number
  nervous: number
  openness: number
  shy: number
  aggressive: number
  secretly_angry: number
  
}

export interface Grade {
  letter_grade: string
  effective_responses: ResponseNote[]
  areas_for_improvement: ResponseNote[]
  feedback: string
  
}

export interface HistoryItem {
  text: string
  speaker: "user" | "ai"
  timestamp: string
  character_state?: CharacterState | null
  user_prosody?: PerceivedProsody | null
  
}

export interface PerceivedProsody {
  scores: ProsodyScores
  perception_notes: string
  
}

export interface ProsodyScores {
  admiration: number
  adoration: number
  amusement: number
  anger: number
  anxiety: number
  awe: number
  awkwardness: number
  boredom: number
  calmness: number
  concentration: number
  confusion: number
  contempt: number
  contentment: number
  determination: number
  disappointment: number
  disgust: number
  distress: number
  doubt: number
  embarrassment: number
  excitement: number
  fear: number
  guilt: number
  interest: number
  joy: number
  love: number
  nostalgia: number
  pain: number
  pride: number
  sadness: number
  satisfaction: number
  shame: number
  surprise_negative: number
  surprise_positive: number
  sympathy: number
  tiredness: number
  
}

export interface ResponseNote {
  original_content: string
  grader_note: string
  
}

export interface Update {
  terminate_session: boolean
  character_state: CharacterState
  reasoning: string
  character_message: string
  
}

export interface VoiceDirections {
  description: string
  speed: number
  
}
