/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    CharacterCharacteristics: ClassViewer<'CharacterCharacteristics', "name" | "is_therapist" | "introversion" | "communication_skill" | "openness" | "conscientiousness" | "age" | "gender" | "nationality" | "reactivity" | "special_notes">;
    
    CharacterState: ClassViewer<'CharacterState', "relaxed" | "nervous" | "openness" | "shy" | "aggressive" | "secretly_angry">;
    
    Grade: ClassViewer<'Grade', "letter_grade" | "effective_responses" | "areas_for_improvement" | "feedback">;
    
    HistoryItem: ClassViewer<'HistoryItem', "text" | "speaker" | "timestamp" | "character_state" | "user_prosody">;
    
    PerceivedProsody: ClassViewer<'PerceivedProsody', "scores" | "perception_notes">;
    
    ProsodyScores: ClassViewer<'ProsodyScores', "admiration" | "adoration" | "amusement" | "anger" | "anxiety" | "awe" | "awkwardness" | "boredom" | "calmness" | "concentration" | "confusion" | "contempt" | "contentment" | "determination" | "disappointment" | "disgust" | "distress" | "doubt" | "embarrassment" | "excitement" | "fear" | "guilt" | "interest" | "joy" | "love" | "nostalgia" | "pain" | "pride" | "sadness" | "satisfaction" | "shame" | "surprise_negative" | "surprise_positive" | "sympathy" | "tiredness">;
    
    ResponseNote: ClassViewer<'ResponseNote', "original_content" | "grader_note">;
    
    Update: ClassViewer<'Update', "terminate_session" | "character_state" | "reasoning" | "character_message">;
    
    VoiceDirections: ClassViewer<'VoiceDirections', "description" | "speed">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "CharacterCharacteristics","CharacterState","Grade","HistoryItem","PerceivedProsody","ProsodyScores","ResponseNote","Update","VoiceDirections",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.CharacterCharacteristics = this.tb.classViewer("CharacterCharacteristics", [
          "name","is_therapist","introversion","communication_skill","openness","conscientiousness","age","gender","nationality","reactivity","special_notes",
        ]);
        
        this.CharacterState = this.tb.classViewer("CharacterState", [
          "relaxed","nervous","openness","shy","aggressive","secretly_angry",
        ]);
        
        this.Grade = this.tb.classViewer("Grade", [
          "letter_grade","effective_responses","areas_for_improvement","feedback",
        ]);
        
        this.HistoryItem = this.tb.classViewer("HistoryItem", [
          "text","speaker","timestamp","character_state","user_prosody",
        ]);
        
        this.PerceivedProsody = this.tb.classViewer("PerceivedProsody", [
          "scores","perception_notes",
        ]);
        
        this.ProsodyScores = this.tb.classViewer("ProsodyScores", [
          "admiration","adoration","amusement","anger","anxiety","awe","awkwardness","boredom","calmness","concentration","confusion","contempt","contentment","determination","disappointment","disgust","distress","doubt","embarrassment","excitement","fear","guilt","interest","joy","love","nostalgia","pain","pride","sadness","satisfaction","shame","surprise_negative","surprise_positive","sympathy","tiredness",
        ]);
        
        this.ResponseNote = this.tb.classViewer("ResponseNote", [
          "original_content","grader_note",
        ]);
        
        this.Update = this.tb.classViewer("Update", [
          "terminate_session","character_state","reasoning","character_message",
        ]);
        
        this.VoiceDirections = this.tb.classViewer("VoiceDirections", [
          "description","speed",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}